default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  primary:
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>

development:
  primary:
    <<: *default
    database: whatfirst_development
    username: hiron
    host: localhost

test:
  primary:
    <<: *default
    database: whatfirst_test
    username: hiron
    host: localhost